name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    tags: ['*']

jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Cancel previous runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: Setup | Checkout
        uses: actions/checkout@v3

      - name: Setup | Rust toolchain
        uses: dtolnay/rust-toolchain@1.70.0
        with:
          components: clippy, rustfmt

      - name: Setup | Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Build | Test
        run: cargo test

      - name: Hygiene | Formatting
        run: cargo fmt -- --check

      - name: Hygiene | Clippy
        run: cargo clippy --all-targets --all-features -- -Dwarnings -Dclippy::all -Dclippy::pedantic -Aclippy::module_name_repetitions -Aclippy::missing_panics_doc -Aclippy::missing_errors_doc -Aclippy::must_use_candidate -Aclippy::similar_names
